name: Build and Access

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.THE_PROJECT }}
  PROJECT_ZONE: europe-west1-b   

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Test Vault Action (default KV V2)
      uses: hashicorp/vault-action@v2.5.0
      with:
        url: http://130.211.105.205/:8200
        token: ${{ secrets.VAULT_TOKEN }}
        
    - name: 'List vault secrets'
      run: 'vault secrets list'
  
   

    
      
